apiVersion: apps/v1
kind: Deployment
metadata:
  name: remix-todo-deployment
  labels: 
    app: remix-todo
spec:
  selector:
    matchLabels:
      app: remix-todo
  replicas: 2
  template:
    metadata:
      labels:
        app: remix-todo
    spec:
      containers:
      - name: remix-todo-container
        image: asgupta2141/test-pri-repo:1.0
        command:
        - argocd-application-controller
        - --status-processors
        - "20"
        - --operation-processors
        - "10"
        - --repo-server-timeout-seconds
        - "180"
        ports:
        - containerPort: 3000

