apiVersion: v1
kind: Service
metadata:
  name: remix-todo-service
spec:
  selector:
    app: remix-todo
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  type: LoadBalancer
